name: Create GIF Archive, Tag, and Upload Artifact

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Git User and Email
      run: |
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
      shell: bash

    - name: Remove existing GIF archive if it exists
      run: |
        if [ -f mastodon-emoji-bundle.tar.gz ]; then
          rm mastodon-emoji-bundle.tar.gz
        fi
      shell: bash

    - name: Create GIF archive
      run: |
        mkdir -p output
        find guests parrots flags -type f -name "*.gif" -exec cp {} output/ \;
        tar czf mastodon-emoji-bundle.tar.gz -C output .
      shell: bash

    - name: Tag with Commit Hash
      run: |
        git tag -a $(git log --format=%h -n 1) -m "Tagging with commit hash"
        git push origin --tags
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mastodon-emoji-bundle
        path: mastodon-emoji-bundle.tar.gz
