name: Create GIF Archive and Release

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Remove existing GIF archive if it exists
      run: |
        if [ -f mastodon-emoji-bundle.tar.gz ]; then
          rm mastodon-emoji-bundle.tar.gz
        fi
      shell: bash

    - name: Create GIF archive
      run: |
        mkdir -p output
        find guests parrots flags -type f -name "*.gif" -exec cp {} output/ \;
        tar czf mastodon-emoji-bundle.tar.gz -C output .
      shell: bash

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        files: mastodon-emoji-bundle.tar.gz

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mastodon-emoji-bundle
        path: mastodon-emoji-bundle.tar.gz

    - name: Set Build Number
      run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Commit and push BUILD_NUMBER
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add $GITHUB_ENV
        git commit -m "Add build number"
        git push
      shell: bash
