name: Create GIF Archive

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove existing GIF archive if it exists
      run: |
        if [ -f mastodon-emoji-bundle.tar.gz ]; then
          rm mastodon-emoji-bundle.tar.gz
        fi
      shell: bash

    - name: Create GIF archive
      run: |
        mkdir -p output
        find guests parrots flags -type f -name "*.gif" -exec cp {} output/ \;
        tar czf mastodon-emoji-bundle.tar.gz -C output .
      shell: bash

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add mastodon-emoji-bundle.tar.gz
        git commit -m "Add GIF archive"
        git push
      shell: bash
